const express=require('express'),path=require('path'),crypto=require('crypto');
module.exports=function initLianliankan({app,awardPrize,recordPlay=async()=>({}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,completions:0,max:0}),isGameEnabled,getActivityCode,isActivityOpen=()=>true}){
  const THEMES=['fruit','pet','dessert','mixed'],DIFFS=['easy','normal','hard'],TIERS=['C1','C2','C3'];
  let settings={theme:'fruit',difficulty:'easy',shuffleLimit:2,timeMinutes:5,selfSelect:false,allowedThemes:[...THEMES],allowedDifficulties:[...DIFFS],tierByDifficulty:{easy:'C1',normal:'C2',hard:'C3'}};
  const runs=new Map();
  const uniq=(arr,allowed,fallback)=>{const x=Array.isArray(arr)?[...new Set(arr.filter(v=>allowed.includes(v)))]:fallback.slice();return x.length?x:fallback.slice()};
  function normalize(s={}){const allowedThemes=uniq(s.allowedThemes,THEMES,settings.allowedThemes||THEMES),allowedDifficulties=uniq(s.allowedDifficulties,DIFFS,settings.allowedDifficulties||DIFFS),tierByDifficulty={};for(const d of DIFFS){const t=String(s.tierByDifficulty?.[d]||settings.tierByDifficulty?.[d]||({easy:'C1',normal:'C2',hard:'C3'})[d]).toUpperCase();tierByDifficulty[d]=TIERS.includes(t)?t:'C1'}let theme=THEMES.includes(s.theme)?s.theme:settings.theme,difficulty=DIFFS.includes(s.difficulty)?s.difficulty:settings.difficulty;if(!allowedThemes.includes(theme))theme=allowedThemes[0];if(!allowedDifficulties.includes(difficulty))difficulty=allowedDifficulties[0];return {theme,difficulty,shuffleLimit:[1,2,3].includes(Number(s.shuffleLimit))?Number(s.shuffleLimit):settings.shuffleLimit,timeMinutes:Math.max(0,Math.min(120,Number(s.timeMinutes??settings.timeMinutes)||0)),selfSelect:s.selfSelect===true,allowedThemes,allowedDifficulties,tierByDifficulty}}
  function getSettings(){return JSON.parse(JSON.stringify(settings))}
  function setSettings(s){settings=normalize(s);return getSettings()}
  function runKey(activity,name){return `${activity}|${String(name).trim().toLowerCase()}`}
  function publicRun(r){return r?{runId:r.runId,startedAt:r.startedAt,endsAt:r.endsAt,settings:r.settings,tier:r.tier,selection:r.selection}:null}
  function choose(req={}){let theme=settings.theme,difficulty=settings.difficulty;if(settings.selfSelect){if(settings.allowedThemes.includes(req.theme))theme=req.theme;if(settings.allowedDifficulties.includes(req.difficulty))difficulty=req.difficulty}return {theme,difficulty}}
  app.use('/games/lianliankan',express.static(path.join(__dirname,'public'),{etag:true,maxAge:0}));
  app.get('/games/lianliankan/api/settings',(req,res)=>res.json({ok:true,settings:getSettings()}));
  app.get('/games/lianliankan/api/active',(req,res)=>{const activity=String(req.query.activity||''),player=String(req.query.player||'').trim();if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});res.json({ok:true,activeRun:publicRun(runs.get(runKey(activity,player)))})});
  app.post('/games/lianliankan/api/start',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30);if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});if(!player)return res.status(400).json({ok:false,message:'請輸入玩家名稱'});if(!isGameEnabled('lianliankan'))return res.status(403).json({ok:false,message:'連連看目前未開放'});if(!isActivityOpen(activity))return res.status(403).json({ok:false,message:'目前不在活動開放時間'});const key=runKey(activity,player),existing=runs.get(key);if(existing)return res.json({ok:true,...publicRun(existing),resumed:true});const st=getCompletionStatus({activityCode:activity,gameId:'lianliankan',playerName:player,playerKey:player});if(!st.allowed)return res.status(409).json({ok:false,message:`已達每位玩家可完成次數上限（${st.max} 次）`,completionStatus:st});const choice=choose(req.body||{}),runSettings={...getSettings(),theme:choice.theme,difficulty:choice.difficulty},startedAt=Date.now(),runId=crypto.randomUUID(),mins=Number(runSettings.timeMinutes)||0,endsAt=mins>0?startedAt+mins*60000:null,tier=runSettings.tierByDifficulty[choice.difficulty]||'C1',selection={主題:choice.theme,難度:choice.difficulty};const r={runId,activity,player,startedAt,endsAt,settings:runSettings,tier,selection};runs.set(key,r);await recordPlay({activityCode:activity,gameId:'lianliankan',gameName:'連連看',playerName:player,playerKey:player});res.json({ok:true,...publicRun(r),resumed:false,completionStatus:st})});
  app.post('/games/lianliankan/api/finish',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30),runId=String(req.body?.runId||''),completed=!!req.body?.completed;if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});const key=runKey(activity,player),r=runs.get(key);if(!r||r.runId!==runId)return res.status(404).json({ok:false,message:'找不到本局資料'});const now=Date.now(),elapsedMs=Math.max(0,now-r.startedAt),within=!r.endsAt||now<=r.endsAt+1500,ok=completed&&within;runs.delete(key);let completion=null,prize=null;if(ok){completion=await recordCompletion({activityCode:activity,gameId:'lianliankan',gameName:'連連看',playerName:player,playerKey:player,elapsedMs,completedAt:now,runKey:r.runId});prize=await awardPrize({activityCode:activity,gameId:'lianliankan',game:'連連看',playerName:player,playerKey:player,gameRef:activity,tier:r.tier,selection:r.selection,elapsedMs})}res.json({ok:true,completed:ok,elapsedMs,completion,prize,tier:r.tier,selection:r.selection,completionStatus:getCompletionStatus({activityCode:activity,gameId:'lianliankan',playerName:player,playerKey:player})})});
  return {getSettings,setSettings,resetForActivity:()=>{runs.clear()}};
};
