const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
module.exports=function initShelf({app,awardPrize,isGameEnabled,getActivityCode,isActivityOpen=()=>true}){
  const DATA_FILE=path.join(__dirname,'data.json');
  const fixedTitle='貨架整理小遊戲';
  const levelDefaults={normal:{open:true,min:3},hard:{open:false,min:4},hell:{open:false,min:5}};
  const defaultRoom=code=>({room:code,title:fixedTitle,themes:{farm:true,candy:true},attempts:3,levels:JSON.parse(JSON.stringify(levelDefaults)),runs:[],records:[],createdAt:Date.now(),updatedAt:Date.now()});
  let db={rooms:{}};try{db=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{};if(!db.rooms)db.rooms={};
  function save(){fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2))}
  function migrate(r){r.title=fixedTitle;r.themes=r.themes&&typeof r.themes==='object'?{farm:!!r.themes.farm,candy:!!r.themes.candy}:{farm:true,candy:true};if(!Object.values(r.themes).some(Boolean))r.themes.farm=true;r.attempts=r.attempts==='unlimited'?'unlimited':Math.max(1,Math.min(99,Number(r.attempts)||3));r.levels=r.levels&&typeof r.levels==='object'?r.levels:{};let selected=Object.keys(levelDefaults).find(k=>r.levels[k]?.open)||'normal';for(const k of Object.keys(levelDefaults)){const x=r.levels[k]||{};r.levels[k]={open:k===selected,min:Math.max(.5,Math.min(60,Number(x.min)||levelDefaults[k].min))}}r.runs=Array.isArray(r.runs)?r.runs:[];r.records=Array.isArray(r.records)?r.records:[];return r}
  function ensureRoom(code=getActivityCode()){code=String(code);if(!db.rooms[code]){db.rooms[code]=defaultRoom(code);save()}return migrate(db.rooms[code])}
  function publicRoom(r){return {room:r.room,title:fixedTitle,themes:r.themes,attempts:r.attempts,levels:r.levels,serverTime:Date.now()}}
  function playerStats(r,n){return {played:r.records.filter(x=>x.player===n).length}}
  function getSettings(){const r=ensureRoom();return {themes:r.themes,attempts:r.attempts,levels:r.levels}}
  function setSettings(b={}){const r=ensureRoom();r.themes={farm:!!b.themes?.farm,candy:!!b.themes?.candy};if(!Object.values(r.themes).some(Boolean))throw new Error('至少開放一個商品主題');r.attempts=b.attempts==='unlimited'?'unlimited':Math.max(1,Math.min(99,Number(b.attempts)||3));const chosen=Object.keys(levelDefaults).find(k=>b.levels?.[k]?.open)||'normal';for(const k of Object.keys(levelDefaults)){const old=r.levels[k]||levelDefaults[k],s=b.levels?.[k]||{};r.levels[k]={open:k===chosen,min:Math.max(.5,Math.min(60,Number(s.min)||old.min))}}r.updatedAt=Date.now();save();return getSettings()}
  function resetForActivity(code){ensureRoom(code)}
  app.use('/games/shelf',express.static(path.join(__dirname,'public')));
  app.get('/games/shelf/api/room/:room',(req,res)=>{const code=String(req.params.room||'');if(code!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});if(!isGameEnabled('shelf'))return res.status(403).json({error:'貨架整理目前未開放'});res.json(publicRoom(ensureRoom(code)))});
  app.get('/games/shelf/api/player/stats',(req,res)=>{const code=String(req.query.room||'');if(code!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});const r=ensureRoom(code),n=String(req.query.player||'').trim().slice(0,20);if(!n)return res.status(400).json({error:'請輸入玩家名稱'});res.json(playerStats(r,n))});
  app.post('/games/shelf/api/player/start',(req,res)=>{const room=String(req.body?.room||''),name=String(req.body?.player||'').trim().slice(0,20),level=String(req.body?.level||''),theme=String(req.body?.theme||'');if(room!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});if(!isGameEnabled('shelf'))return res.status(403).json({error:'貨架整理目前未開放'});if(!isActivityOpen(room))return res.status(403).json({error:'目前不在活動開放時間'});const r=ensureRoom(room);if(!name)return res.status(400).json({error:'請輸入玩家名稱'});if(!r.levels[level]?.open)return res.status(400).json({error:'此難度未開放'});if(!r.themes[theme])return res.status(400).json({error:'此商品主題未開放'});const stats=playerStats(r,name);if(r.attempts!=='unlimited'&&stats.played>=r.attempts)return res.status(409).json({error:'已達遊玩次數上限'});if(r.runs.find(x=>x.player===name&&!x.finishedAt))return res.status(409).json({error:'你已有進行中的挑戰'});const runId=crypto.randomUUID(),startedAt=Date.now(),durationMs=Math.round(r.levels[level].min*60000);r.runs.unshift({runId,player:name,level,theme,startedAt,durationMs,finishedAt:null});r.runs=r.runs.slice(0,20000);save();res.json({runId,startedAt,durationMs})});
  app.post('/games/shelf/api/player/finish',async(req,res)=>{const room=String(req.body?.room||''),runId=String(req.body?.runId||''),cleared=!!req.body?.cleared;if(room!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});const r=ensureRoom(room),run=r.runs.find(x=>x.runId===runId);if(!run)return res.status(404).json({error:'找不到本局資料'});if(run.finishedAt)return res.json(run.result);const now=Date.now();if(now<run.startedAt+1500)return res.status(400).json({error:'遊戲時間異常'});run.finishedAt=now;const within=now<=run.startedAt+run.durationMs+1500,ok=cleared&&within;const rec={player:run.player,game:'貨架整理',theme:run.theme,level:run.level,startedAt:run.startedAt,finishedAt:now,elapsedMs:now-run.startedAt,cleared:ok,endReason:ok?'clear':'time'};r.records.unshift(rec);r.records=r.records.slice(0,20000);run.result={...rec};if(ok)run.result.prize=await awardPrize({game:'貨架整理',playerName:run.player,playerKey:run.player,gameRef:room});save();res.json(run.result)});
  return {ensureRoom,getSettings,setSettings,resetForActivity};
};
