const express=require('express'),path=require('path'),crypto=require('crypto');
module.exports=function initPuzzle({app,awardPrize,recordPlay=async()=>({}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,completions:0,max:0}),isGameEnabled,getActivityCode,isActivityOpen=()=>true}){
  let settings={grid:5,imageIds:[0,1,2,3,4,5,6,7,8,9],timeMinutes:3,allowPeek:true,hintCount:3};
  const runs=new Map();
  function normalize(s={}){const ids=Array.isArray(s.imageIds)?[...new Set(s.imageIds.map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<10))]:settings.imageIds;return {grid:[4,5,6].includes(Number(s.grid))?Number(s.grid):settings.grid,imageIds:ids.length?ids:settings.imageIds,timeMinutes:Math.max(0,Math.min(60,Number(s.timeMinutes??settings.timeMinutes)||0)),allowPeek:s.allowPeek!==undefined?!!s.allowPeek:settings.allowPeek,hintCount:Math.max(0,Math.min(10,Math.floor(Number(s.hintCount??settings.hintCount)||0)))}}
  function getSettings(){return {...settings,imageIds:[...settings.imageIds]}}
  function setSettings(s){settings=normalize(s);return getSettings()}
  function key(activity,name){return `${activity}|${String(name).trim().toLowerCase()}`}
  function pub(r){return r?{runId:r.runId,startedAt:r.startedAt,endsAt:r.endsAt,settings:r.settings,imageId:r.imageId,seed:r.seed}:null}
  app.use('/games/puzzle',express.static(path.join(__dirname,'public'),{etag:true,maxAge:0}));
  app.get('/games/puzzle/api/settings',(req,res)=>res.json({ok:true,settings:getSettings()}));
  app.get('/games/puzzle/api/active',(req,res)=>{const activity=String(req.query.activity||''),player=String(req.query.player||'').trim();if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});res.json({ok:true,activeRun:pub(runs.get(key(activity,player)))})});
  app.post('/games/puzzle/api/start',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30),imageId=Number(req.body?.imageId);if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});if(!player)return res.status(400).json({ok:false,message:'請輸入玩家名稱'});if(!isGameEnabled('puzzle'))return res.status(403).json({ok:false,message:'拼圖挑戰目前未開放'});if(!isActivityOpen(activity))return res.status(403).json({ok:false,message:'目前不在活動開放時間'});const k=key(activity,player),old=runs.get(k);if(old)return res.json({ok:true,...pub(old),resumed:true});const st=getCompletionStatus({activityCode:activity,gameId:'puzzle',playerName:player,playerKey:player});if(!st.allowed)return res.status(409).json({ok:false,message:`已達每位玩家可完成次數上限（${st.max} 次）`,completionStatus:st});const allowed=settings.imageIds.includes(imageId)?imageId:settings.imageIds[Math.floor(Math.random()*settings.imageIds.length)],startedAt=Date.now(),mins=Number(settings.timeMinutes)||0,r={runId:crypto.randomUUID(),activity,player,startedAt,endsAt:mins>0?startedAt+mins*60000:null,settings:getSettings(),imageId:allowed,seed:crypto.randomInt(1,0x7fffffff)};runs.set(k,r);await recordPlay({activityCode:activity,gameId:'puzzle',gameName:'拼圖挑戰',playerName:player,playerKey:player});res.json({ok:true,...pub(r),resumed:false,completionStatus:st})});
  app.post('/games/puzzle/api/finish',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30),runId=String(req.body?.runId||''),completed=!!req.body?.completed;if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});const k=key(activity,player),r=runs.get(k);if(!r||r.runId!==runId)return res.status(404).json({ok:false,message:'找不到本局資料'});const now=Date.now(),elapsedMs=Math.max(0,now-r.startedAt),within=!r.endsAt||now<=r.endsAt+1500,ok=completed&&within;runs.delete(k);let completion=null,prize=null;if(ok){completion=await recordCompletion({activityCode:activity,gameId:'puzzle',gameName:'拼圖挑戰',playerName:player,playerKey:player,elapsedMs,completedAt:now,runKey:r.runId});prize=await awardPrize({activityCode:activity,gameId:'puzzle',game:'拼圖挑戰',playerName:player,playerKey:player,gameRef:activity});}res.json({ok:true,completed:ok,elapsedMs,completion,prize,completionStatus:getCompletionStatus({activityCode:activity,gameId:'puzzle',playerName:player,playerKey:player})})});
  return {getSettings,setSettings,resetForActivity:()=>{runs.clear()}};
};
