const express=require('express'),path=require('path'),crypto=require('crypto');
const IMAGES=require('./images.json');
module.exports=function initPuzzle({app,awardPrize,recordPlay=async()=>({}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,completions:0,max:0}),isGameEnabled,getActivityCode,isActivityOpen=()=>true}){
  const CATEGORIES=['可愛動物','海洋世界','森林／農場','樂園／甜點','冬季／極光','旅行／風景'],GRIDS=[4,5,6],TIERS=['C1','C2','C3'];
  let settings={selfSelect:true,grid:5,allowedGrids:[4,5,6],category:'可愛動物',allowedCategories:[...CATEGORIES],tierByGrid:{4:'C1',5:'C2',6:'C3'},timeMinutes:15,allowPeek:true,hintCount:3};
  const runs=new Map();
  function normalize(s={}){const allowedGrids=Array.isArray(s.allowedGrids)?[...new Set(s.allowedGrids.map(Number).filter(x=>GRIDS.includes(x)))]:settings.allowedGrids;const allowedCategories=Array.isArray(s.allowedCategories)?[...new Set(s.allowedCategories.filter(x=>CATEGORIES.includes(x)))]:settings.allowedCategories;const tierByGrid={};for(const g of GRIDS){const t=String(s.tierByGrid?.[g]||settings.tierByGrid?.[g]||({4:'C1',5:'C2',6:'C3'}[g])).toUpperCase();tierByGrid[g]=TIERS.includes(t)?t:({4:'C1',5:'C2',6:'C3'}[g])}const grids=allowedGrids.length?allowedGrids:[settings.grid||5],cats=allowedCategories.length?allowedCategories:[settings.category||CATEGORIES[0]];return {selfSelect:s.selfSelect===true,grid:grids.includes(+s.grid)?+s.grid:grids[0],allowedGrids:grids,category:cats.includes(s.category)?s.category:cats[0],allowedCategories:cats,tierByGrid,timeMinutes:Math.max(0,Math.min(120,Number(s.timeMinutes??settings.timeMinutes)||0)),allowPeek:s.allowPeek!==undefined?!!s.allowPeek:settings.allowPeek,hintCount:Math.max(0,Math.min(10,Math.floor(Number(s.hintCount??settings.hintCount)||0)))}}
  function getSettings(){return JSON.parse(JSON.stringify(settings))}function setSettings(s){settings=normalize(s);return getSettings()}function key(activity,name){return `${activity}|${String(name).trim().toLowerCase()}`}
  function pub(r){return r?{runId:r.runId,startedAt:r.startedAt,endsAt:r.endsAt,settings:r.settings,image:r.image,category:r.category,grid:r.grid,tier:r.tier,seed:r.seed}:null}
  app.use('/games/puzzle',express.static(path.join(__dirname,'public'),{etag:true,maxAge:0}));
  app.get('/games/puzzle/api/settings',(req,res)=>res.json({ok:true,settings:getSettings(),categories:CATEGORIES}));
  app.get('/games/puzzle/api/active',(req,res)=>{const activity=String(req.query.activity||''),player=String(req.query.player||'').trim();if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});res.json({ok:true,activeRun:pub(runs.get(key(activity,player)))})});
  app.post('/games/puzzle/api/start',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30);if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});if(!player)return res.status(400).json({ok:false,message:'請輸入玩家名稱'});if(!isGameEnabled('puzzle'))return res.status(403).json({ok:false,message:'拼圖挑戰目前未開放'});if(!isActivityOpen(activity))return res.status(403).json({ok:false,message:'目前不在活動開放時間'});const k=key(activity,player),old=runs.get(k);if(old)return res.json({ok:true,...pub(old),resumed:true});const st=getCompletionStatus({activityCode:activity,gameId:'puzzle',playerName:player,playerKey:player});if(!st.allowed)return res.status(409).json({ok:false,message:`已達每位玩家可完成次數上限（${st.max} 次）`,completionStatus:st});let grid=settings.grid,category=settings.category;if(settings.selfSelect){if(settings.allowedGrids.includes(+req.body?.grid))grid=+req.body.grid;if(settings.allowedCategories.includes(req.body?.category))category=req.body.category}const pool=IMAGES.filter(x=>x.category===category);if(!pool.length)return res.status(400).json({ok:false,message:'這個分類目前沒有拼圖'});const image=pool[crypto.randomInt(0,pool.length)],startedAt=Date.now(),mins=Number(settings.timeMinutes)||0,tier=settings.tierByGrid[grid]||'C1',r={runId:crypto.randomUUID(),activity,player,startedAt,endsAt:mins>0?startedAt+mins*60000:null,settings:getSettings(),image,category,grid,tier,seed:crypto.randomInt(1,0x7fffffff)};runs.set(k,r);await recordPlay({activityCode:activity,gameId:'puzzle',gameName:'拼圖挑戰',playerName:player,playerKey:player});res.json({ok:true,...pub(r),resumed:false,completionStatus:st})});
  app.post('/games/puzzle/api/finish',async(req,res)=>{const activity=String(req.body?.activity||''),player=String(req.body?.player||'').trim().slice(0,30),runId=String(req.body?.runId||''),completed=!!req.body?.completed;if(activity!==String(getActivityCode()))return res.status(404).json({ok:false,message:'活動不存在'});const k=key(activity,player),r=runs.get(k);if(!r||r.runId!==runId)return res.status(404).json({ok:false,message:'找不到本局資料'});const now=Date.now(),elapsedMs=Math.max(0,now-r.startedAt),within=!r.endsAt||now<=r.endsAt+1500,ok=completed&&within;runs.delete(k);let completion=null,prize=null;if(ok){completion=await recordCompletion({activityCode:activity,gameId:'puzzle',gameName:'拼圖挑戰',playerName:player,playerKey:player,elapsedMs,completedAt:now,runKey:r.runId});prize=await awardPrize({activityCode:activity,gameId:'puzzle',game:'拼圖挑戰',playerName:player,playerKey:player,gameRef:activity,tier:r.tier,selection:{分類:r.category,盤面:`${r.grid}×${r.grid}`,圖片:r.image.name},elapsedMs})}res.json({ok:true,completed:ok,elapsedMs,completion,prize,completionStatus:getCompletionStatus({activityCode:activity,gameId:'puzzle',playerName:player,playerKey:player})})});
  return {getSettings,setSettings,resetForActivity:()=>runs.clear()};
};
