const express=require('express');
const path=require('path');
module.exports=function initSudoku({app,io,awardPrize,recordPlay=async()=>({status:'skipped'}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,max:0,completions:0}),isGameEnabled,getActivityCode=()=>'',isActivityOpen=()=>true}){
app.use('/games/sudoku',express.static(path.join(__dirname,'public'),{maxAge:0}));
const activities=new Map();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a};
function makeCode(){let c;do{c=String(Math.floor(100000+Math.random()*900000));}while(activities.has(c));return c;}
function symbols(n){return Array.from({length:n},(_,i)=>i+1)}
function boxDims(n){return n===12?[3,4]:[3,3]}
function baseSolution(n){const[br,bc]=boxDims(n);return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>((r*bc+Math.floor(r/br)+c)%n)+1))}
function shuffledSolution(n){let g=baseSolution(n);const[br,bc]=boxDims(n);const sym=shuffle(symbols(n));g=g.map(row=>row.map(v=>sym[v-1]));const bands=shuffle(Array.from({length:n/br},(_,i)=>i));let rows=[];bands.forEach(b=>shuffle(Array.from({length:br},(_,i)=>b*br+i)).forEach(r=>rows.push(r)));g=rows.map(r=>g[r]);const stacks=shuffle(Array.from({length:n/bc},(_,i)=>i));let cols=[];stacks.forEach(s=>shuffle(Array.from({length:bc},(_,i)=>s*bc+i)).forEach(c=>cols.push(c)));g=g.map(row=>cols.map(c=>row[c]));if(n===9&&Math.random()<.5)g=Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>g[c][r]));return g}
function symbolShuffle(grid){const n=grid.length,m=shuffle(symbols(n));return grid.map(row=>row.map(v=>m[v-1]))}
const DIAG_TEMPLATES={9:[[6,1,4,3,2,9,7,5,8],[9,7,5,1,6,8,3,4,2],[3,8,2,4,7,5,9,6,1],[4,6,3,8,9,7,1,2,5],[7,5,8,6,1,2,4,3,9],[1,2,9,5,3,4,8,7,6],[8,9,6,2,4,3,5,1,7],[5,3,1,7,8,6,2,9,4],[2,4,7,9,5,1,6,8,3]],12:[[9,5,12,7,10,6,8,2,11,1,4,3],[10,3,2,6,1,4,12,11,9,8,5,7],[4,11,1,8,3,9,7,5,6,10,12,2],[1,2,6,12,9,7,3,4,8,11,10,5],[11,4,8,10,5,12,2,1,3,9,7,6],[5,7,9,3,11,10,6,8,12,2,1,4],[12,8,7,1,6,2,11,3,4,5,9,10],[2,10,5,11,4,8,9,7,1,6,3,12],[3,6,4,9,12,5,1,10,2,7,8,11],[6,1,11,5,8,3,10,12,7,4,2,9],[8,12,10,2,7,11,4,9,5,3,6,1],[7,9,3,4,2,1,5,6,10,12,11,8]]};
const NONCONSEC_TEMPLATES={9:[[8,6,1,3,5,9,2,4,7],[3,9,4,7,2,6,8,1,5],[5,2,7,1,8,4,6,3,9],[7,5,3,9,4,8,1,6,2],[1,8,6,2,7,5,3,9,4],[9,4,2,6,1,3,7,5,8],[2,7,9,4,6,1,5,8,3],[4,1,5,8,3,7,9,2,6],[6,3,8,5,9,2,4,7,1]],12:[[7,9,3,10,12,4,6,11,8,2,5,1],[5,11,6,12,1,9,2,8,3,10,7,4],[2,4,8,1,3,5,7,10,6,12,9,11],[9,12,2,8,6,1,11,4,10,5,3,7],[1,10,5,11,2,8,3,7,4,9,6,12],[6,3,7,4,9,12,10,5,11,1,8,2],[11,1,4,9,7,3,8,12,2,6,10,5],[3,7,10,6,4,11,5,2,12,8,1,9],[8,5,12,2,10,6,1,9,7,4,11,3],[4,8,1,7,5,10,12,3,9,11,2,6],[10,2,9,5,11,7,4,6,1,3,12,8],[12,6,11,3,8,2,9,1,5,7,4,10]]};
function nonconsecutiveSolution(n){let g=NONCONSEC_TEMPLATES[n].map(r=>r.slice());if(Math.random()<.5)g=g.map(r=>r.map(v=>n+1-v));if(Math.random()<.5)g=g.map(r=>r.slice().reverse());if(Math.random()<.5)g=g.slice().reverse();return g}
function colorSolution(n){return symbolShuffle(baseSolution(n))}function colorGroups(n){return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>(r+6*c)%n))}
function connectedRegion(regions,id){const n=regions.length,cells=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(regions[r][c]===id)cells.push([r,c]);if(!cells.length)return false;const seen=new Set([cells[0].join(',')]),q=[cells[0]];for(let i=0;i<q.length;i++){const[r,c]=q[i];for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const nr=r+dr,nc=c+dc,k=`${nr},${nc}`;if(nr>=0&&nr<n&&nc>=0&&nc<n&&regions[nr][nc]===id&&!seen.has(k)){seen.add(k);q.push([nr,nc])}}}return seen.size===cells.length}
function buildIrregularRegions(solution){const n=solution.length,[br,bc]=boxDims(n),regions=Array.from({length:n},()=>Array(n).fill(0));let id=0;for(let rb=0;rb<n;rb+=br)for(let cb=0;cb<n;cb+=bc){for(let r=rb;r<rb+br;r++)for(let c=cb;c<cb+bc;c++)regions[r][c]=id;id++}let swaps=0,target=n===9?8:12;for(let t=0;t<180&&swaps<target;t++){const candidates=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++){const a=regions[r][c];for(const[dr,dc]of[[1,0],[0,1]]){const nr=r+dr,nc=c+dc;if(nr<n&&nc<n&&regions[nr][nc]!==a)candidates.push([a,regions[nr][nc]])}}if(!candidates.length)break;const[A,B]=candidates[Math.floor(Math.random()*candidates.length)],ca=[],cb=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++){if(regions[r][c]===A)ca.push([r,c]);else if(regions[r][c]===B)cb.push([r,c])}const pairs=[];for(const x of ca)for(const y of cb)if(solution[x[0]][x[1]]===solution[y[0]][y[1]]){const tb=[[1,0],[-1,0],[0,1],[0,-1]].some(([dr,dc])=>{const rr=x[0]+dr,cc=x[1]+dc;return rr>=0&&rr<n&&cc>=0&&cc<n&&regions[rr][cc]===B});const ta=[[1,0],[-1,0],[0,1],[0,-1]].some(([dr,dc])=>{const rr=y[0]+dr,cc=y[1]+dc;return rr>=0&&rr<n&&cc>=0&&cc<n&&regions[rr][cc]===A});if(tb&&ta)pairs.push([x,y])}if(!pairs.length)continue;const[x,y]=pairs[Math.floor(Math.random()*pairs.length)];regions[x[0]][x[1]]=B;regions[y[0]][y[1]]=A;if(connectedRegion(regions,A)&&connectedRegion(regions,B))swaps++;else{regions[x[0]][x[1]]=A;regions[y[0]][y[1]]=B}}return regions}
function buildCages(sol){const n=sol.length,seen=Array.from({length:n},()=>Array(n).fill(false)),cages=[],dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(!seen[r][c]){const target=Math.random()<.18?1:(Math.random()<.62?2:3),cells=[[r,c]],used=new Set([sol[r][c]]);seen[r][c]=true;while(cells.length<target){const frontier=[];for(const[rr,cc]of cells)for(const[dr,dc]of dirs){const nr=rr+dr,nc=cc+dc;if(nr>=0&&nr<n&&nc>=0&&nc<n&&!seen[nr][nc]&&!used.has(sol[nr][nc]))frontier.push([nr,nc])}if(!frontier.length)break;const pick=frontier[Math.floor(Math.random()*frontier.length)];seen[pick[0]][pick[1]]=true;used.add(sol[pick[0]][pick[1]]);cells.push(pick)}cages.push({cells,sum:cells.reduce((s,[rr,cc])=>s+sol[rr][cc],0)})}return cages}
function clueCount(n,d){const ratio=d==='初級'?.56:d==='中級'?.43:.34;return Math.round(n*n*ratio)}
function regionMapStandard(n){const[br,bc]=boxDims(n),perRow=n/bc;return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>Math.floor(r/br)*perRow+Math.floor(c/bc)))}
function popcount(x){let c=0;while(x){x&=x-1;c++}return c}
function countSolutions(puzzle,regions,limit=2){const n=puzzle.length,full=(1<<n)-1,row=Array(n).fill(0),col=Array(n).fill(0),reg=Array(n).fill(0),grid=puzzle.map(r=>r.slice());for(let r=0;r<n;r++)for(let c=0;c<n;c++){const v=grid[r][c];if(!v)continue;const bit=1<<(v-1),g=regions[r][c];if((row[r]|col[c]|reg[g])&bit)return 0;row[r]|=bit;col[c]|=bit;reg[g]|=bit}let found=0;function dfs(){if(found>=limit)return;let rr=-1,cc=-1,bm=0,bcnt=99;for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(!grid[r][c]){const m=full&~(row[r]|col[c]|reg[regions[r][c]]),cnt=popcount(m);if(!cnt)return;if(cnt<bcnt){rr=r;cc=c;bm=m;bcnt=cnt}}if(rr<0){found++;return}const g=regions[rr][cc];for(let v=1;v<=n&&found<limit;v++){const bit=1<<(v-1);if(!(bm&bit))continue;grid[rr][cc]=v;row[rr]|=bit;col[cc]|=bit;reg[g]|=bit;dfs();row[rr]^=bit;col[cc]^=bit;reg[g]^=bit;grid[rr][cc]=0}}dfs();return found}
function uniquePuzzle(solution,difficulty,regions){const n=solution.length,p=solution.map(r=>r.slice()),target=clueCount(n,difficulty),order=shuffle(Array.from({length:n*n},(_,i)=>i));let clues=n*n;for(const idx of order){if(clues<=target)break;const r=Math.floor(idx/n),c=idx%n,old=p[r][c];p[r][c]=0;if(countSolutions(p,regions,2)!==1)p[r][c]=old;else clues--}return p}
function makePuzzle(size,difficulty,variant){const n=size;let solution,meta={};if(variant==='對角線數獨')solution=symbolShuffle(DIAG_TEMPLATES[n]);else if(variant==='不連續數獨')solution=nonconsecutiveSolution(n);else if(variant==='彩色數獨')solution=colorSolution(n);else solution=shuffledSolution(n);if(variant==='殺手數獨')meta.cages=buildCages(solution);if(variant==='不規則數獨')meta.regions=buildIrregularRegions(solution);if(variant==='彩色數獨')meta.colors=colorGroups(n);const regions=variant==='不規則數獨'?meta.regions:regionMapStandard(n);return {puzzle:uniquePuzzle(solution,difficulty,regions),solution,meta}}
function validGrid(g,n){return Array.isArray(g)&&g.length===n&&g.every(r=>Array.isArray(r)&&r.length===n)}
function defaults(){return {variant:'標準數獨',size:9,difficulty:'初級',showWrongCount:false,roundMinutes:10,selfSelect:false,allowedVariants:['標準數獨','對角線數獨','殺手數獨','不連續數獨','不規則數獨','彩色數獨'],allowedSizes:[9,12],allowedDifficulties:['初級','中級','高級'],tierByDifficulty:{'初級':'C1','中級':'C2','高級':'C3'}}}
const variants=['標準數獨','對角線數獨','殺手數獨','不連續數獨','不規則數獨','彩色數獨'];
const a={code:'SUDOKU',settings:defaults(),note:'',players:new Map(),hostSocket:null};
function normalizeHallSettings(settings={}){const difficulties=['初級','中級','高級'];let size=+settings.size===12?12:9,variant=variants.includes(settings.variant)?settings.variant:'標準數獨',difficulty=difficulties.includes(settings.difficulty)?settings.difficulty:'初級';if(size===12&&['殺手數獨','不規則數獨'].includes(variant))size=9;let allowedVariants=Array.isArray(settings.allowedVariants)?settings.allowedVariants.filter(x=>variants.includes(x)):variants.slice();if(!allowedVariants.length)allowedVariants=[variant];let allowedSizes=Array.isArray(settings.allowedSizes)?settings.allowedSizes.map(Number).filter(x=>[9,12].includes(x)):[9,12];if(!allowedSizes.length)allowedSizes=[size];let allowedDifficulties=Array.isArray(settings.allowedDifficulties)?settings.allowedDifficulties.filter(x=>difficulties.includes(x)):difficulties.slice();if(!allowedDifficulties.length)allowedDifficulties=[difficulty];const tierByDifficulty={};for(const d of difficulties){const t=String(settings.tierByDifficulty?.[d]||({初級:'C1',中級:'C2',高級:'C3'}[d])).toUpperCase();tierByDifficulty[d]=['C1','C2','C3'].includes(t)?t:({初級:'C1',中級:'C2',高級:'C3'}[d])}return {variant,size,difficulty,showWrongCount:settings.showWrongCount===true,roundMinutes:[0,1,2,3,5,10,15,20,30,45,60].includes(+settings.roundMinutes)?+settings.roundMinutes:10,selfSelect:settings.selfSelect===true,allowedVariants,allowedSizes,allowedDifficulties,tierByDifficulty};}
function hallGetSettings(){return {...a.settings};}
function hallSetSettings(settings={}){a.settings=normalizeHallSettings(settings);broadcast();return {...a.settings};}
function resetForActivity(){a.players.clear();a.hostSocket=null;return {...a.settings};}
function publicActivity(){return {settings:a.settings,note:a.note}}
function broadcast(){io.to('sudoku-global').emit('activity:update',publicActivity())}
function findBySocket(sid){return [...a.players.values()].find(p=>p.socketId===sid)}
function publicRun(r){if(!r)return null;return {runId:r.id,settings:r.settings||a.settings,note:r.note||'',puzzle:r.puzzle.puzzle,meta:r.puzzle.meta,solution:r.puzzle.solution,startedAt:r.startedAt,endsAt:r.endsAt,tier:r.tier,selection:r.selection};}
io.on('connection',socket=>{
 socket.on('host:join',()=>{a.hostSocket=socket.id;socket.join('sudoku-global');socket.emit('host:ready',publicActivity())});
 socket.on('host:update',({settings,note},ack)=>{if(a.hostSocket!==socket.id)return ack?.({ok:false,message:'沒有主控權限'});a.settings=normalizeHallSettings(settings);a.note=String(note||'').slice(0,500);broadcast();ack?.({ok:true})});
 socket.on('player:join',({name,token,code})=>{
  if(String(code||'')!==String(getActivityCode()))return socket.emit('error:msg','活動碼已失效，請返回小遊戲館');if(!isGameEnabled('sudoku'))return socket.emit('error:msg','數獨目前未開放');socket.data.sudokuActivity=String(code||'');name=String(name||'').trim().slice(0,20);token=String(token||'').trim().slice(0,100);if(!name)return socket.emit('error:msg','請輸入玩家名稱');
  let p=a.players.get(token);if(!p){const duplicate=[...a.players.values()].find(x=>x.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(duplicate)return socket.emit('error:msg','此玩家名稱已有人使用');p={token,name,wins:0,history:[],socketId:socket.id,connected:true,run:null};a.players.set(token,p)}else{p.socketId=socket.id;p.connected=true;p.name=name}
  let expired=false;if(p.run&&p.run.endsAt&&Date.now()>=p.run.endsAt){p.run=null;expired=true}socket.join('sudoku-global');socket.emit('player:ready',{activity:publicActivity(),self:{name:p.name,wins:p.wins,history:p.history.slice(-20)},activeRun:publicRun(p.run),expired});
 });
 socket.on('player:start-round',async(payload={})=>{
  if(String(socket.data.sudokuActivity||'')!==String(getActivityCode()))return socket.emit('round:error','活動已切換，請返回小遊戲館');if(!isGameEnabled('sudoku'))return socket.emit('round:error','數獨目前未開放');if(!isActivityOpen(socket.data.sudokuActivity))return socket.emit('round:error','目前不在活動開放時間');const p=findBySocket(socket.id);if(!p)return;if(p.run)return socket.emit('round:start',{...publicRun(p.run),resumed:true});
  const activityCode=String(socket.data.sudokuActivity||getActivityCode()),limit=getCompletionStatus({activityCode,gameId:'sudoku',playerName:p.name,playerKey:p.name});if(!limit.allowed)return socket.emit('round:error',`已達每位玩家可完成次數上限（${limit.max} 次）`);const base=a.settings;let variant=base.variant,size=base.size,difficulty=base.difficulty;if(base.selfSelect){if(base.allowedVariants.includes(payload.variant))variant=payload.variant;if(base.allowedSizes.includes(+payload.size))size=+payload.size;if(base.allowedDifficulties.includes(payload.difficulty))difficulty=payload.difficulty}if(size===12&&['殺手數獨','不規則數獨'].includes(variant)){size=9;if(base.selfSelect&&!base.allowedSizes.includes(9))return socket.emit('round:error','這個玩法目前只能使用 9×9')}const settings={...base,variant,size,difficulty},tier=base.tierByDifficulty?.[difficulty]||'C1',selection={玩法:variant,盤面:`${size}×${size}`,難度:difficulty},puzzle=makePuzzle(size,difficulty,variant),startedAt=Date.now(),endsAt=Number(settings.roundMinutes)>0?startedAt+settings.roundMinutes*60000:null;p.run={id:`${startedAt}_${Math.random().toString(36).slice(2,8)}`,puzzle,settings,note:a.note,startedAt,endsAt,tier,selection};await recordPlay({activityCode,gameId:'sudoku',gameName:'數獨',playerName:p.name,playerKey:p.name});socket.emit('round:start',{...publicRun(p.run),resumed:false});
 });
 socket.on('player:finish-round',async ({runId,grid})=>{
  if(String(socket.data.sudokuActivity||'')!==String(getActivityCode()))return socket.emit('round:result',{ok:false,message:'活動已切換，本局不再發獎'});const p=findBySocket(socket.id);if(!p||!p.run||p.run.id!==runId)return socket.emit('round:result',{ok:false,message:'這一局已失效，請重新開始'});const r=p.run,n=r.puzzle.solution.length,completedAt=Date.now();if(r.endsAt&&completedAt>r.endsAt){p.run=null;return socket.emit('round:result',{ok:false,expired:true,message:'時間到，本局未完成'})}
  let empty=0,wrong=0;if(!validGrid(grid,n))wrong=1;else for(let i=0;i<n;i++)for(let j=0;j<n;j++){const v=+grid[i][j]||0;if(!v)empty++;else if(v!==r.puzzle.solution[i][j])wrong++}if(empty||wrong)return socket.emit('round:result',{ok:false,emptyCount:empty,wrongCount:wrong,message:empty?`還有 ${empty} 格尚未填寫。`:`還有 ${wrong} 格錯誤，請再檢查！`});
  const elapsedMs=completedAt-r.startedAt;p.wins++;p.history.push({completedAt,variant:r.settings.variant,size:r.settings.size,difficulty:r.settings.difficulty,elapsedMs,qualified:true});if(p.history.length>100)p.history.shift();p.run=null;const activityCode=String(socket.data.sudokuActivity||getActivityCode());await recordCompletion({activityCode,gameId:'sudoku',gameName:'數獨',playerName:p.name,playerKey:p.name,elapsedMs,completedAt,runKey:r.id});socket.emit('round:result',{ok:true,qualified:true,elapsedMs,completedAt,wins:p.wins,completionStatus:getCompletionStatus({activityCode,gameId:'sudoku',playerName:p.name,playerKey:p.name})});const prize=await awardPrize({activityCode,gameId:'sudoku',game:'數獨',playerName:p.name,playerKey:p.name,gameRef:'SUDOKU',tier:r.tier||'C1',selection:r.selection||{玩法:r.settings.variant,盤面:`${r.settings.size}×${r.settings.size}`,難度:r.settings.difficulty},elapsedMs});socket.emit('prize:result',prize);
 });
 socket.on('player:expire-round',({runId})=>{const p=findBySocket(socket.id);if(p&&p.run&&p.run.id===runId&&p.run.endsAt&&Date.now()>=p.run.endsAt){p.run=null;socket.emit('round:expired')}});
 socket.on('disconnect',()=>{const p=findBySocket(socket.id);if(p){p.connected=false;p.socketId=null}if(a.hostSocket===socket.id)a.hostSocket=null});
});
return {activity:a,getSettings:hallGetSettings,setSettings:hallSetSettings,resetForActivity};
};
