const express=require('express');
const crypto=require('crypto');
const path=require('path');
module.exports=function initMemory({app,io,awardPrize,isGameEnabled,getActivityCode,isAdmin,isActivityOpen=()=>true}){
  app.use('/games/memory',express.static(path.join(__dirname,'public'),{etag:true,maxAge:0}));
  const rooms=new Map();
  function normalizeSettings(s={}){return {type:['farm','idiom','poem'].includes(s.type)?s.type:'farm',boardSize:['4x4','6x6','8x8'].includes(s.boardSize)?s.boardSize:'4x4',gameMinutes:['1','2','3','5','10','unlimited'].includes(String(s.gameMinutes))?String(s.gameMinutes):'3',maxPlays:['1','2','3','5','unlimited'].includes(String(s.maxPlays))?String(s.maxPlays):'1'}}
  function ensureRoom(code){code=String(code||getActivityCode()).trim();if(!rooms.has(code))rooms.set(code,{code,settings:normalizeSettings(),players:new Map(),startCount:0,finishCount:0});return rooms.get(code)}
  function maxPlays(settings){const v=String(settings?.maxPlays||'1');return v==='unlimited'?Infinity:Math.max(1,Number(v)||1)}
  function onlineCount(r){return [...r.players.values()].filter(p=>p.online).length}
  function playerView(p){return {clientId:p.clientId,name:p.name,online:!!p.online,gamesPlayed:p.gamesPlayed||0,successCount:p.successCount||0,bestTime:p.bestTime??null,lastTime:p.lastTime??null,status:p.activeRun?'遊戲中':(p.lastCompleted?'已完成':(p.gamesPlayed?'未完成':'尚未開始'))}}
  function records(r){return [...r.players.values()].map(playerView).sort((a,b)=>(b.successCount-a.successCount)||((a.bestTime??1e15)-(b.bestTime??1e15))||(a.gamesPlayed-b.gamesPlayed)||a.name.localeCompare(b.name,'zh-Hant'))}
  function roomInfo(r){return {code:r.code,settings:r.settings,online:onlineCount(r),startCount:r.startCount||0,finishCount:r.finishCount||0,players:records(r)}}
  function emitRoom(r){io.to('memory:'+r.code).emit('room',roomInfo(r))}
  function findPlayer(r,{clientId,name}={}){if(clientId&&r.players.has(clientId))return r.players.get(clientId);if(name){const n=String(name).trim().toLowerCase();return [...r.players.values()].find(p=>p.name.toLowerCase()===n)}return null}
  function getSettings(){return {...ensureRoom().settings}}
  function setSettings(settings){const r=ensureRoom();r.settings=normalizeSettings(settings);emitRoom(r);return {...r.settings}}
  function resetForActivity(code){ensureRoom(code);}
  io.on('connection',s=>{
    s.on('join',({code,name,clientId},cb)=>{code=String(code||getActivityCode());if(code!==String(getActivityCode()))return cb?.({ok:false,msg:'活動碼已失效'});if(!isGameEnabled('memory'))return cb?.({ok:false,msg:'翻牌目前未開放'});const r=ensureRoom(code);name=String(name||'').trim().slice(0,20);if(!name)return cb?.({ok:false,msg:'請輸入玩家名稱'});const lower=name.toLowerCase();let p=clientId?r.players.get(String(clientId)):null;if(!p){const duplicate=[...r.players.values()].find(x=>x.name.toLowerCase()===lower);if(duplicate)return cb?.({ok:false,msg:'這個玩家名稱已有人使用'});const id=crypto.randomBytes(12).toString('hex');p={clientId:id,name,online:true,socketId:s.id,gamesPlayed:0,successCount:0,bestTime:null,lastTime:null,lastCompleted:false,activeRun:null};r.players.set(id,p)}else{p.name=name;p.online=true;p.socketId=s.id}s.join('memory:'+r.code);s.data.memoryRoom=r.code;s.data.memoryClient=p.clientId;emitRoom(r);cb?.({ok:true,clientId:p.clientId,room:roomInfo(r),player:playerView(p),activeRun:p.activeRun})});
    s.on('startRun',({code,clientId},cb)=>{code=String(code||getActivityCode());const r=rooms.get(code),p=r&&r.players.get(String(clientId||''));if(!r||!p)return cb?.({ok:false,msg:'玩家資料不存在'});if(!isGameEnabled('memory'))return cb?.({ok:false,msg:'翻牌目前未開放'});if(!isActivityOpen(code))return cb?.({ok:false,msg:'目前不在活動開放時間'});if(p.activeRun)return cb?.({ok:false,msg:'目前已有進行中的遊戲'});const limit=maxPlays(r.settings);if(p.gamesPlayed>=limit)return cb?.({ok:false,msg:'已達遊玩次數上限'});p.gamesPlayed++;r.startCount++;const runId=`${r.code}-${p.clientId}-${Date.now()}-${Math.floor(Math.random()*1e9)}`;p.activeRun={runId,startedAt:Date.now(),settings:{...r.settings}};p.lastCompleted=false;p.lastTime=null;emitRoom(r);cb?.({ok:true,runId,startedAt:p.activeRun.startedAt,settings:p.activeRun.settings,gamesPlayed:p.gamesPlayed,maxPlays:r.settings.maxPlays,seed:Math.floor(Math.random()*0x7fffffff)})});
    s.on('finishRun',({runId,completed,time},cb)=>{const r=rooms.get(s.data.memoryRoom),p=r&&r.players.get(s.data.memoryClient);if(!r||!p||!p.activeRun||String(runId)!==String(p.activeRun.runId))return cb?.({ok:false,msg:'本局資料不存在'});if(r.code!==String(getActivityCode())){p.activeRun=null;return cb?.({ok:false,msg:'活動已切換，本局不再發獎'});}const elapsed=Math.max(0,Number(time)||0);const mins=String(p.activeRun.settings.gameMinutes)==='unlimited'?Infinity:Number(p.activeRun.settings.gameMinutes||3);const within=mins===Infinity||elapsed<=mins*60000+1500;const ok=!!completed&&within;p.lastCompleted=ok;p.lastTime=elapsed;if(ok){p.successCount++;r.finishCount++;if(p.bestTime==null||elapsed<p.bestTime)p.bestTime=elapsed}p.activeRun=null;emitRoom(r);cb?.({ok:true,completed:ok,player:playerView(p),settings:r.settings});if(ok){const prize=awardPrize({game:'翻牌',playerName:p.name,playerKey:p.name,gameRef:r.code});const payload=prize.status==='out_of_stock'?{status:'soldout'}:prize.status==='limit_reached'?{status:'limit'}:prize.status==='activity_closed'?{status:'closed'}:{status:'awarded',prizeName:prize.prizeName};s.emit('prizeAwarded',payload)}});
    s.on('disconnect',()=>{const r=rooms.get(s.data.memoryRoom),p=r&&r.players.get(s.data.memoryClient);if(p){p.online=false;p.socketId=null;emitRoom(r)}});
  });
  return {rooms,ensureRoom,getSettings,setSettings,resetForActivity};
};
