const express=require('express');
const crypto=require('crypto');
const path=require('path');
module.exports=function initMemory({app,io,awardPrize,recordPlay=async()=>({status:'skipped'}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,max:0,completions:0}),isGameEnabled,getActivityCode,isAdmin,isActivityOpen=()=>true}){
  app.use('/games/memory',express.static(path.join(__dirname,'public'),{etag:true,maxAge:0}));
  const rooms=new Map(),TYPES=['farm','idiom','poem'],SIZES=['4x4','6x6','8x8'],TIERS=['C1','C2','C3'];
  const uniq=(a,allowed,fb)=>{const x=Array.isArray(a)?[...new Set(a.filter(v=>allowed.includes(v)))]:fb.slice();return x.length?x:fb.slice()};
  function normalizeSettings(s={}){const prev={type:'farm',boardSize:'4x4',gameMinutes:'5',selfSelect:false,allowedTypes:TYPES,allowedBoardSizes:SIZES,tierByBoardSize:{'4x4':'C1','6x6':'C2','8x8':'C3'}};const allowedTypes=uniq(s.allowedTypes,TYPES,prev.allowedTypes),allowedBoardSizes=uniq(s.allowedBoardSizes,SIZES,prev.allowedBoardSizes),tierByBoardSize={};for(const z of SIZES){const t=String(s.tierByBoardSize?.[z]||prev.tierByBoardSize[z]).toUpperCase();tierByBoardSize[z]=TIERS.includes(t)?t:prev.tierByBoardSize[z]}let type=TYPES.includes(s.type)?s.type:prev.type,boardSize=SIZES.includes(s.boardSize)?s.boardSize:prev.boardSize;if(!allowedTypes.includes(type))type=allowedTypes[0];if(!allowedBoardSizes.includes(boardSize))boardSize=allowedBoardSizes[0];const gm=['1','2','3','5','10','15','20','30','unlimited'].includes(String(s.gameMinutes))?String(s.gameMinutes):'5';return {type,boardSize,gameMinutes:gm,selfSelect:s.selfSelect===true,allowedTypes,allowedBoardSizes,tierByBoardSize}}
  function ensureRoom(code){code=String(code||getActivityCode()).trim();if(!rooms.has(code))rooms.set(code,{code,settings:normalizeSettings(),players:new Map(),startCount:0,finishCount:0});return rooms.get(code)}
  function onlineCount(r){return [...r.players.values()].filter(p=>p.online).length}
  function playerView(p){return {clientId:p.clientId,name:p.name,online:!!p.online,gamesPlayed:p.gamesPlayed||0,successCount:p.successCount||0,bestTime:p.bestTime??null,lastTime:p.lastTime??null,status:p.activeRun?'遊戲中':(p.lastCompleted?'已完成':(p.gamesPlayed?'未完成':'尚未開始'))}}
  function records(r){return [...r.players.values()].map(playerView).sort((a,b)=>(b.successCount-a.successCount)||((a.bestTime??1e15)-(b.bestTime??1e15))||(a.gamesPlayed-b.gamesPlayed)||a.name.localeCompare(b.name,'zh-Hant'))}
  function roomInfo(r){return {code:r.code,settings:r.settings,online:onlineCount(r),startCount:r.startCount||0,finishCount:r.finishCount||0,players:records(r)}}
  function emitRoom(r){io.to('memory:'+r.code).emit('room',roomInfo(r))}
  function getSettings(){return JSON.parse(JSON.stringify(ensureRoom().settings))}
  function setSettings(settings){const r=ensureRoom();r.settings=normalizeSettings(settings);emitRoom(r);return getSettings()}
  function resetForActivity(code){ensureRoom(code)}
  function chosenSettings(base,choice={}){const out={...base};if(base.selfSelect){if(base.allowedTypes.includes(choice.type))out.type=choice.type;if(base.allowedBoardSizes.includes(choice.boardSize))out.boardSize=choice.boardSize}return out}
  io.on('connection',s=>{
    s.on('join',({code,name,clientId},cb)=>{code=String(code||getActivityCode());if(code!==String(getActivityCode()))return cb?.({ok:false,msg:'活動碼已失效'});if(!isGameEnabled('memory'))return cb?.({ok:false,msg:'翻牌目前未開放'});const r=ensureRoom(code);name=String(name||'').trim().slice(0,20);if(!name)return cb?.({ok:false,msg:'請輸入玩家名稱'});const lower=name.toLowerCase();let p=clientId?r.players.get(String(clientId)):null;if(!p){const duplicate=[...r.players.values()].find(x=>x.name.toLowerCase()===lower);if(duplicate)return cb?.({ok:false,msg:'這個玩家名稱已有人使用'});const id=crypto.randomBytes(12).toString('hex');p={clientId:id,name,online:true,socketId:s.id,gamesPlayed:0,successCount:0,bestTime:null,lastTime:null,lastCompleted:false,activeRun:null};r.players.set(id,p)}else{p.name=name;p.online=true;p.socketId=s.id}s.join('memory:'+r.code);s.data.memoryRoom=r.code;s.data.memoryClient=p.clientId;emitRoom(r);cb?.({ok:true,clientId:p.clientId,room:roomInfo(r),player:playerView(p),activeRun:p.activeRun})});
    s.on('startRun',async({code,clientId,choice},cb)=>{code=String(code||getActivityCode());const r=rooms.get(code),p=r&&r.players.get(String(clientId||''));if(!r||!p)return cb?.({ok:false,msg:'玩家資料不存在'});if(!isGameEnabled('memory'))return cb?.({ok:false,msg:'翻牌目前未開放'});if(!isActivityOpen(code))return cb?.({ok:false,msg:'目前不在活動開放時間'});if(p.activeRun)return cb?.({ok:true,runId:p.activeRun.runId,startedAt:p.activeRun.startedAt,settings:p.activeRun.settings,gamesPlayed:p.gamesPlayed,seed:p.activeRun.seed||1,tier:p.activeRun.tier,resumed:true});const limit=getCompletionStatus({activityCode:code,gameId:'memory',playerName:p.name,playerKey:p.name});if(!limit.allowed)return cb?.({ok:false,msg:`已達每位玩家可完成次數上限（${limit.max} 次）`});p.gamesPlayed++;r.startCount++;const runId=`${r.code}-${p.clientId}-${Date.now()}-${Math.floor(Math.random()*1e9)}`,seed=Math.floor(Math.random()*0x7fffffff),runSettings=chosenSettings(r.settings,choice||{}),tier=runSettings.tierByBoardSize?.[runSettings.boardSize]||'C1';p.activeRun={runId,startedAt:Date.now(),settings:runSettings,seed,tier,selection:{題型:runSettings.type,盤面:runSettings.boardSize}};p.lastCompleted=false;p.lastTime=null;await recordPlay({activityCode:r.code,gameId:'memory',gameName:'翻牌',playerName:p.name,playerKey:p.name});emitRoom(r);cb?.({ok:true,runId,startedAt:p.activeRun.startedAt,settings:p.activeRun.settings,gamesPlayed:p.gamesPlayed,seed:p.activeRun.seed,tier,completionStatus:limit})});
    s.on('finishRun',async ({runId,completed,time},cb)=>{const r=rooms.get(s.data.memoryRoom),p=r&&r.players.get(s.data.memoryClient);if(!r||!p||!p.activeRun||String(runId)!==String(p.activeRun.runId))return cb?.({ok:false,msg:'本局資料不存在'});if(r.code!==String(getActivityCode())){p.activeRun=null;return cb?.({ok:false,msg:'活動已切換，本局不再發獎'});}const active=p.activeRun,elapsed=Math.max(0,Date.now()-active.startedAt),mins=String(active.settings.gameMinutes)==='unlimited'?Infinity:Number(active.settings.gameMinutes||5),within=mins===Infinity||elapsed<=mins*60000+1500,ok=!!completed&&within;p.lastCompleted=ok;p.lastTime=elapsed;if(ok){p.successCount++;r.finishCount++;if(p.bestTime==null||elapsed<p.bestTime)p.bestTime=elapsed}p.activeRun=null;let prize=null;if(ok){await recordCompletion({activityCode:r.code,gameId:'memory',gameName:'翻牌',playerName:p.name,playerKey:p.name,elapsedMs:elapsed,completedAt:Date.now(),runKey:active.runId});prize=await awardPrize({activityCode:r.code,gameId:'memory',game:'翻牌',playerName:p.name,playerKey:p.name,gameRef:r.code,tier:active.tier,selection:active.selection,elapsedMs:elapsed});const payload=prize.status==='game_out_of_stock'?{status:'game-soldout'}:prize.status==='out_of_stock'?{status:'soldout'}:prize.status==='tier_out_of_stock'?{status:'tier-soldout',tier:active.tier}:prize.status==='limit_reached'?{status:'limit'}:prize.status==='activity_closed'?{status:'closed'}:prize.status==='storage_error'?{status:'error',message:prize.message}:{status:'awarded',prizeName:prize.prizeName,tier:prize.tier};s.emit('prizeAwarded',payload)}emitRoom(r);cb?.({ok:true,completed:ok,elapsedMs:elapsed,player:playerView(p),settings:r.settings,prize,completionStatus:getCompletionStatus({activityCode:r.code,gameId:'memory',playerName:p.name,playerKey:p.name})})});
    s.on('disconnect',()=>{const r=rooms.get(s.data.memoryRoom),p=r&&r.players.get(s.data.memoryClient);if(p){p.online=false;p.socketId=null;emitRoom(r)}});
  });
  return {rooms,ensureRoom,getSettings,setSettings,resetForActivity};
};
