const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
module.exports=function initShelf({app,awardPrize,recordPlay=async()=>({status:'skipped'}),recordCompletion=async()=>({}),getCompletionStatus=()=>({allowed:true,max:0,completions:0}),isGameEnabled,getActivityCode,isActivityOpen=()=>true}){
  const DATA_FILE=path.join(__dirname,'data.json'),fixedTitle='貨架整理小遊戲',LEVELS=['normal','hard','hell'],TIERS=['C1','C2','C3'];
  const levelDefaults={normal:{open:true,tier:'C1'},hard:{open:true,tier:'C2'},hell:{open:true,tier:'C3'}};
  const defaultRoom=code=>({room:code,title:fixedTitle,selfSelect:false,defaultLevel:'normal',defaultTheme:'farm',timeMinutes:10,themes:{farm:true,candy:true},levels:JSON.parse(JSON.stringify(levelDefaults)),runs:[],records:[],createdAt:Date.now(),updatedAt:Date.now()});
  let db={rooms:{}};try{db=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{};if(!db.rooms)db.rooms={};
  function save(){fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2))}
  function migrate(r){r.title=fixedTitle;r.themes=r.themes&&typeof r.themes==='object'?{farm:!!r.themes.farm,candy:!!r.themes.candy}:{farm:true,candy:true};if(!Object.values(r.themes).some(Boolean))r.themes.farm=true;r.levels=r.levels&&typeof r.levels==='object'?r.levels:{};for(const k of LEVELS){const x=r.levels[k]||{},t=String(x.tier||levelDefaults[k].tier).toUpperCase();r.levels[k]={open:x.open!==false,tier:TIERS.includes(t)?t:levelDefaults[k].tier}}if(!LEVELS.some(k=>r.levels[k].open))r.levels.normal.open=true;r.defaultLevel=LEVELS.includes(r.defaultLevel)&&r.levels[r.defaultLevel].open?r.defaultLevel:LEVELS.find(k=>r.levels[k].open)||'normal';r.defaultTheme=['farm','candy'].includes(r.defaultTheme)&&r.themes[r.defaultTheme]?r.defaultTheme:(r.themes.farm?'farm':'candy');r.selfSelect=r.selfSelect===true;const legacyMin=Number(r.levels?.[r.defaultLevel]?.min);r.timeMinutes=Math.max(0,Math.min(120,Number.isFinite(Number(r.timeMinutes))?Number(r.timeMinutes):(Number.isFinite(legacyMin)?legacyMin:10)));r.runs=Array.isArray(r.runs)?r.runs:[];r.records=Array.isArray(r.records)?r.records:[];delete r.attempts;return r}
  function ensureRoom(code=getActivityCode()){code=String(code);if(!db.rooms[code]){db.rooms[code]=defaultRoom(code);save()}return migrate(db.rooms[code])}
  function publicRoom(r){return {room:r.room,title:fixedTitle,selfSelect:r.selfSelect,defaultLevel:r.defaultLevel,defaultTheme:r.defaultTheme,timeMinutes:r.timeMinutes,themes:r.themes,levels:r.levels,serverTime:Date.now()}}
  function playerStats(r,n){const mine=r.records.filter(x=>x.player===n);return {played:mine.length,success:mine.filter(x=>x.cleared).length}}
  function getSettings(){return publicRoom(ensureRoom())}
  function setSettings(b={}){const r=ensureRoom();r.selfSelect=b.selfSelect===true;r.themes={farm:!!b.themes?.farm,candy:!!b.themes?.candy};if(!Object.values(r.themes).some(Boolean))throw new Error('至少開放一個商品主題');for(const k of LEVELS){const x=b.levels?.[k]||{},t=String(x.tier||r.levels[k]?.tier||levelDefaults[k].tier).toUpperCase();r.levels[k]={open:x.open!==false,tier:TIERS.includes(t)?t:levelDefaults[k].tier}}if(!LEVELS.some(k=>r.levels[k].open))throw new Error('至少開放一個難度');r.defaultLevel=LEVELS.includes(b.defaultLevel)&&r.levels[b.defaultLevel].open?b.defaultLevel:LEVELS.find(k=>r.levels[k].open);r.defaultTheme=['farm','candy'].includes(b.defaultTheme)&&r.themes[b.defaultTheme]?b.defaultTheme:(r.themes.farm?'farm':'candy');r.timeMinutes=Math.max(0,Math.min(120,Number(b.timeMinutes??r.timeMinutes)||0));r.updatedAt=Date.now();save();return getSettings()}
  function resetForActivity(code){ensureRoom(code)}
  app.use('/games/shelf',express.static(path.join(__dirname,'public'),{maxAge:0}));
  app.get('/games/shelf/api/room/:room',(req,res)=>{const code=String(req.params.room||'');if(code!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});if(!isGameEnabled('shelf'))return res.status(403).json({error:'貨架整理目前未開放'});res.json(publicRoom(ensureRoom(code)))});
  app.get('/games/shelf/api/player/stats',(req,res)=>{const code=String(req.query.room||'');if(code!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});const r=ensureRoom(code),n=String(req.query.player||'').trim().slice(0,20);if(!n)return res.status(400).json({error:'請輸入玩家名稱'});res.json(playerStats(r,n))});
  app.get('/games/shelf/api/player/active',(req,res)=>{const code=String(req.query.room||''),name=String(req.query.player||'').trim().slice(0,20);if(code!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});if(!name)return res.status(400).json({error:'請輸入玩家名稱'});const r=ensureRoom(code),run=r.runs.find(x=>x.player===name&&!x.finishedAt);if(!run)return res.json({activeRun:null});res.json({activeRun:{runId:run.runId,player:run.player,level:run.level,theme:run.theme,startedAt:run.startedAt,durationMs:run.durationMs,seed:run.seed||1,tier:run.tier}})});
  app.post('/games/shelf/api/player/start',async(req,res)=>{const room=String(req.body?.room||''),name=String(req.body?.player||'').trim().slice(0,20),theme=String(req.body?.theme||'');if(room!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});if(!isGameEnabled('shelf'))return res.status(403).json({error:'貨架整理目前未開放'});if(!isActivityOpen(room))return res.status(403).json({error:'目前不在活動開放時間'});const r=ensureRoom(room);if(!name)return res.status(400).json({error:'請輸入玩家名稱'});let level=r.selfSelect?String(req.body?.level||''):r.defaultLevel;let useTheme=r.selfSelect?theme:r.defaultTheme;if(!r.levels[level]?.open)level=r.defaultLevel;if(!r.levels[level]?.open)return res.status(400).json({error:'此難度未開放'});if(!r.themes[useTheme])return res.status(400).json({error:'此商品主題未開放'});const limit=getCompletionStatus({activityCode:room,gameId:'shelf',playerName:name,playerKey:name});if(!limit.allowed)return res.status(409).json({error:`已達每位玩家可完成次數上限（${limit.max} 次）`});const existing=r.runs.find(x=>x.player===name&&!x.finishedAt);if(existing)return res.json({runId:existing.runId,startedAt:existing.startedAt,durationMs:existing.durationMs,level:existing.level,theme:existing.theme,seed:existing.seed||1,tier:existing.tier,resumed:true});const runId=crypto.randomUUID(),startedAt=Date.now(),durationMs=Math.round(Math.max(0,Number(r.timeMinutes)||0)*60000),seed=crypto.randomInt(1,0x7fffffff),tier=r.levels[level].tier||'C1';r.runs.unshift({runId,player:name,level,theme:useTheme,tier,startedAt,durationMs,seed,finishedAt:null});r.runs=r.runs.slice(0,20000);save();await recordPlay({activityCode:room,gameId:'shelf',gameName:'貨架整理',playerName:name,playerKey:name});res.json({runId,startedAt,durationMs,level,theme:useTheme,seed,tier,resumed:false,completionStatus:limit})});
  app.post('/games/shelf/api/player/finish',async(req,res)=>{const room=String(req.body?.room||''),runId=String(req.body?.runId||''),cleared=!!req.body?.cleared;if(room!==String(getActivityCode()))return res.status(404).json({error:'活動不存在'});const r=ensureRoom(room),run=r.runs.find(x=>x.runId===runId);if(!run)return res.status(404).json({error:'找不到本局資料'});if(run.finishedAt)return res.json(run.result);const now=Date.now();if(now<run.startedAt+500)return res.status(400).json({error:'遊戲時間異常'});run.finishedAt=now;const within=!run.durationMs||now<=run.startedAt+run.durationMs+1500,ok=cleared&&within,elapsedMs=now-run.startedAt;const rec={player:run.player,game:'貨架整理',theme:run.theme,level:run.level,tier:run.tier,startedAt:run.startedAt,finishedAt:now,elapsedMs,cleared:ok,endReason:ok?'clear':'time'};r.records.unshift(rec);r.records=r.records.slice(0,20000);run.result={...rec};if(ok){run.result.completion=await recordCompletion({activityCode:room,gameId:'shelf',gameName:'貨架整理',playerName:run.player,playerKey:run.player,elapsedMs,completedAt:now,runKey:run.runId});run.result.prize=await awardPrize({activityCode:room,gameId:'shelf',game:'貨架整理',playerName:run.player,playerKey:run.player,gameRef:room,tier:run.tier,selection:{主題:run.theme,難度:run.level},elapsedMs})}run.result.completionStatus=getCompletionStatus({activityCode:room,gameId:'shelf',playerName:run.player,playerKey:run.player});save();res.json(run.result)});
  return {ensureRoom,getSettings,setSettings,resetForActivity};
};
